Stage 5 & 6 (Clear History function)
VictorVictini/CS210Shell pull request #48
Opened 2024-03-17 15:01 UTC by n8han11

Added Clear History function for Stages 5 & 6.

2024-03-17 16:54 UTC, mohfez requested changes

2024-03-17 16:54 UTC, mohfez commented on Stages/history.c
> +    FILE *fp = fopen(fileLoc, "w");
Can use set_file() from file_handling.c here, would look cleaner.

2024-03-17 16:54 UTC, mohfez commented on Stages/history.c
> +    printf("History cleared.\n");
make it return an int to indicate success/failure then handle the print messages in shell.c based on the int returned.

(you can maybe do `return set_file(...);`)

2024-03-17 16:54 UTC, mohfez commented on shell.c
> +			else if (strcmp("clear", args[0]) == 0 && strcmp("history", args[1]) == 0)
use argsLen to check if it's ONLY 2 arguments; no more, no less.
if it's not then add appropriate print error messages.

2024-03-17 16:54 UTC, mohfez commented on shell.c
> +                		clear_history(home_dir);
use the int that it returns to print the success/failure message as discussed earlier.

2024-03-17 19:36 UTC, mohfez commented
I made the changes in the other branch.

Thanks.

2024-03-18 01:39 UTC, closed without merging

2024-03-18 02:11 UTC, VictorVictini commented
np